ci: add stale.yml for probot/stale
autowarefoundation/autoware_core_universe_prototype pull request #111
Opened 2022-03-23 11:38 UTC by kenji-miyake

## Description

As the discussion result with @xmfcx, I'll add https://github.com/probot/stale with `[](https://github.com/)daysUntilClose: false`.
https://discordapp.com/channels/953808765935816715/953808766657241121/955806112748273707

## Pre-review checklist for the PR author

PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has the write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-03-23 12:00 UTC, xmfcx requested changes

2022-03-23 12:00 UTC, xmfcx commented on .github/stale.yml
> +daysUntilClose: false
In https://github.com/apps/stale it says:
> After installing the integration, create .github/stale.yml in the default branch to enable it:

So it needs this file or it won't be enabled. I also added the other parameters to make it explicit.

```suggestion
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: false
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale # original was `wontfix`
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

2022-03-23 12:05 UTC, kenji-miyake commented on .github/stale.yml
> +daysUntilClose: false
I think it's better to write only changed settings because people can easily understand what has changed.

@xmfcx 
- Are there any reasons for making them explicit?
- How about writing `Modified from https://github.com/probot/stale#usage` instead?

2022-03-24 04:00 UTC, kenji-miyake commented on .github/stale.yml
> +daysUntilClose: false
6f18a5050850502761d99f7c8c28ac6b5bcb5b4b

2022-03-24 04:14 UTC, kenji-miyake commented
Added sync settings to each repository.
![image](https://user-images.githubusercontent.com/31987104/159840897-d18bdd92-34a0-4df6-99b2-f9b74dfefa80.png)

2022-03-24 09:17 UTC, xmfcx requested changes

2022-03-24 09:17 UTC, xmfcx commented on .github/stale.yml
> +daysUntilClose: false
```suggestion
# Modified from https://github.com/probot/stale#usage

# Number of days of inactivity before a stale issue is closed
daysUntilClose: false
# Label to use when marking an issue as stale
staleLabel: stale
```

Is this ok? @kenji-miyake

2022-03-24 09:17 UTC, xmfcx commented on .github/stale.yml
> +daysUntilClose: false
```suggestion
# Number of days of inactivity before a stale issue is closed
daysUntilClose: false
# Label to use when marking an issue as stale
staleLabel: stale
```
Could we also change the label from `wontfix` to `stale` to reflect our intent better?

2022-03-24 09:20 UTC, xmfcx approved these changes
Thanks!

2022-03-24 09:27 UTC, merged