feat: add basic Docker support
autowarefoundation/autoware_core_universe_prototype pull request #14
Opened 2022-01-09 21:21 UTC by kenji-miyake

Also tested in this repository.
https://github.com/kenji-miyake/test-multiarch-docker

2022-01-14 13:15 UTC, kenji-miyake commented
I'll merge this after ARM build errors are resolved next week.

2022-01-19 01:11 UTC, KeisukeShima commented on .github/workflows/docker-build-and-push.yaml
> +      - v*
How about making the pattern follow semver?
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

```suggestion
      - v[0-9]+.[0-9]+.[0-9]+
```

2022-01-19 01:18 UTC, kenji-miyake commented on .github/workflows/docker-build-and-push.yaml
> +      - v*
Thank you, but actually, we have to consider the cases with suffixes such as `v0.1.2-beta`.

2022-01-19 01:21 UTC, kenji-miyake commented on .github/workflows/docker-build-and-push.yaml
> +      - v*
Since I think we don't create tags so often, I feel this is enough for now.
If we want to use some tags like `v-foo-bar`, we can change the condition later.

2022-01-19 02:18 UTC, KeisukeShima commented on .github/workflows/docker-build-and-push.yaml
> +      - v*
OK. I understood.

2022-01-21 03:59 UTC, kenji-miyake commented
CI has passed.
https://github.com/autowarefoundation/autoware/runs/4890625980?check_suite_focus=true

2022-01-24 06:09 UTC, LalithVipulananthan commented
@IshitaTakeshi @kenji-miyake 

Before I start and at the risk of asking an incredibly dumb question, what is the purpose of the build.sh file? If I were to clone this repository in order to use either the development image or the pre-built image, would I need to run that build.sh file?

- For any grammar/typos etc, please refer to the comments that I made directly on the file.
- In addition to those comments, I think that there should be some kind of introductory text to explain the purpose of the repository.
    - For example (and please bear in mind that I am not very familiar with Docker so this may be incorrect):

> This repository was created to enable the development and testing of Autoware without needing to set up a local development environment from scratch. Two Docker images are available for use - a development image for Autoware development and a prebuilt image for testing of Autoware's features.

2022-01-24 06:11 UTC, kenji-miyake commented
> what is the purpose of the build.sh file?

@LalithVipulananthan I'm sorry, I forgot to explain about it.
Generally, user can use Docker images built by the CI, but if necessary, user can build images locally by running `build.sh`.

> For any grammar/typos etc, please refer to the comments that I made directly on the file (review still in progress)

Thank you, understood!

2022-01-24 06:35 UTC, LalithVipulananthan commented
@kenji-miyake @IshitaTakeshi 
I've finished my initial review, so please check my suggestions and let me know if you have any comments or feedback. 🙂 

>Generally, user can use Docker images built by the CI, but if necessary, user can build images locally by running build.sh.
So if I just cloned the repository and ran one of the listed commands without running build.sh first, would the requested image be downloaded from Docker Hub?

2022-01-24 06:38 UTC, LalithVipulananthan requested changes
Reviewed the README.md file as requested.

2022-01-24 06:38 UTC, ghost commented on docker/README.md
> +If you do not mount your workspace by `-v` option, the workspace used for building `prebuilt` image is opened, but it is usually useless.
> ", but it is usually useless"
This is a very vague statement to make. If the consequences of excluding the "-v" option cannot be described briefly, then I would suggest removing this entire line.

2022-01-24 06:38 UTC, ghost commented on docker/README.md
> +Please note that `setup.bash` is not automatically sourced with `rocker`.
If rocker is installed as a dependency and we think that it is useful, should we not update `setup.bash `so that it is automatically sourced with `rocker`?

2022-01-24 06:38 UTC, ghost commented on docker/README.md
> +This image is for quickly testing Autoware's feature. Please note that it is not designed to deploy on real vehicles.
```suggestion
Please note that the prebuilt Autoware Docker image is not designed for deployment on a real vehicle!
```

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +You can use this image as below.
```suggestion
To use the development image, run the following command:
```

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +It is useful to use `rocker` if you launch `rviz` or other GUI applications.
To use the development image with `rocker` in order to run `rviz` or any other GUI applications, run the following command:

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +This image is for developing Autoware without setting up the local development environment.
If an introductory text is added to explain the purpose of the repository and the difference between the two images, then I think that this line can be removed.

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +You can use this image as below.
```suggestion
To use the prebuilt image, run the following command:
```

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +If you use `rocker`:
```suggestion
To use the prebuilt image with `rocker`:
```

2022-01-24 06:38 UTC, LalithVipulananthan commented on docker/README.md
> +If you use some map data and log data, add `--volume` options as below or use `--home` option and place the data under your home directory.
```suggestion
If you intend to use pre-existing data such as maps or Rosbags, either modify the `--volume` options shown below or alternatively replace them with the `--home` option and place the required data under your home directory.
```

2022-01-24 06:38 UTC, kenji-miyake commented
> So if I just cloned the repository and ran one of the listed commands without running build.sh first, would the requested image be downloaded from Docker Hub?

Yes, but since this PR isn't merged yet, it takes a bit of time to build and publish Docker images.

2022-01-24 06:43 UTC, kenji-miyake commented on docker/README.md
> +If you do not mount your workspace by `-v` option, the workspace used for building `prebuilt` image is opened, but it is usually useless.
Yes I know, I'm sorry. It was difficult to explain. :cry: 
I'll remove this.

2022-01-26 13:11 UTC, kenji-miyake commented on docker/README.md
> +You can use this image as below.
Do we need to repeat the word `development` here?
I know it's so because you say so, but let me confirm why it's necessary.

2022-01-26 13:16 UTC, LalithVipulananthan commented on docker/README.md
> +If you do not mount your workspace by `-v` option, the workspace used for building `prebuilt` image is opened, but it is usually useless.
No need to apologise! To be honest, if someone decides to omit parts of the command as stated in the usage guide, I do not think it is necessary to explain what may happen as a consequence.

2022-01-26 13:19 UTC, kenji-miyake commented on docker/README.md
> +If you do not mount your workspace by `-v` option, the workspace used for building `prebuilt` image is opened, but it is usually useless.
I'm relieved. :smile:

2022-01-26 13:33 UTC, kenji-miyake commented on docker/README.md
> +If you do not mount your workspace by `-v` option, the workspace used for building `prebuilt` image is opened, but it is usually useless.
a3408bf27422bd592ac2cd80e85a73d91d97a549

2022-01-26 13:36 UTC, kenji-miyake commented on docker/README.md
> +Please note that `setup.bash` is not automatically sourced with `rocker`.
I'm sorry I couldn't understand this question well.
What I meant here is, although we source `setup.bash` [here](https://github.com/autowarefoundation/autoware/pull/14/files#diff-36a199a2dbe6455795f2485b956ac1791a8e001492166414332288a216a9aa55R51), it has no effect if you use `rocker`, so you have to manually source it after launching the DOcker image.

2022-01-26 17:31 UTC, kenji-miyake commented on docker/README.md
> +This image is for developing Autoware without setting up the local development environment.
How about this?
https://github.com/autowarefoundation/autoware/pull/14/files#diff-da8fcbe728a9172b578e5d754f8e2df214c658c4321f610e63dd68bea828ab49R15-R20

2022-01-26 17:32 UTC, kenji-miyake commented on docker/README.md
> +Please note that `setup.bash` is not automatically sourced with `rocker`.
Fixed this behavior in https://github.com/autowarefoundation/autoware/pull/14/commits/94351941e3c75ad63db42abfc93de68097184c1f and removed the description.

Instead, I wrote about how to use a customized `.bashrc`.
https://github.com/autowarefoundation/autoware/pull/14/files#diff-da8fcbe728a9172b578e5d754f8e2df214c658c4321f610e63dd68bea828ab49R44-R48

2022-01-26 17:33 UTC, kenji-miyake commented
@LalithVipulananthan @IshitaTakeshi I've updated the README. Could you review it again, please? :pray:

2022-01-28 08:24 UTC, LalithVipulananthan reviewed
Apologies if I overdid the review. Please check my comments and let me know if you have any questions.

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +We have two types of Docker images: `development` and `prebuilt`.
General comments about the usage section:

- "image" not "images".
- Lines 15-22 should go immediately below the title rather than here, as these lines explain what the images do rather than how to use them.
- We should add a line at the very beginning to say `These images provide all of the required dependencies for running Autoware in Docker.`

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +The setup script in this repository will install these dependencies.
I am a little confused by this line. I had a read through the scripts and I couldn't see anything that would install Docker or rocker. Could someone clarify how these dependencies are installed if someone were to clone the repository and try to either execute one of the `docker run`  commands or to run the build script?

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +  We use `rocker` to enable GUI applications such as `rviz` and `rqt` on Docker Containers.
```suggestion
We use `rocker` to enable GUI applications such as `rviz` and `rqt` on Docker Containers.
```

Removed the indentation at the start of the sentence as it looks like it's part of the bullet list and it shouldn't be.

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +### The development image
```suggestion
### Development image
```

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +### The prebuilt image
```suggestion
### Prebuilt image
```

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +To use the development image image, run the following command:
On reflection, you can just remove this line since it's obvious what it does, plus it repeats "development" immediately after the title so looks a bit weird.

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +To use the prebuilt image, run the following command:
For the same reasons as above, I think this line can be removed.

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
On the assumption that this is only a problem when using the development image and doing builds...

```suggestion
If either image is run without `rocker`, then `root` permissions will be used. However, this can cause problems when using the development image.
```

2022-01-28 08:24 UTC, ghost commented on docker/README.md
> +It means it affects
This line can be removed.

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +There are several recommended ways to prevent this.
```suggestion
There are several ways to prevent this error from occurring:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +1. Prepare a dedicated workspace for the docker image.
If `rocker` is recommended, then shouldn't it be at the top of the list? Or is preparing a dedicated workspace our top recommendation?

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +rocker --nvidia --x11 --user --volume {path_to_your_workspace} --volume {path_to_your_map_data} --volume {path_to_your_log_data} -- ghcr.io/autowarefoundation/autoware-universe:latest-prebuilt
For any of the long commands that result in a scrollbar, perhaps consider splitting the command across multiple lines. See the [WireGuard docker README](https://github.com/linuxserver/docker-wireguard) for examples.

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +### Using other versions of images than `latest`
```suggestion
### Using versions other than `latest`
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
```suggestion
There are also image versions available based on `date` or `SemVer`.
```

What is `SemVar` by the way?

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +If you build the images locally instead of pulling them from the server, run the following command:
```suggestion
If you want to build the images locally instead of pulling them from the server, run the following command:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +### Building Docker images on your local machine
I think this should be included in its own sub-heading (##) below Usage but above Tips. The very bottom of the page doesn't seem like the right place for this information.

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +To run with `rocker`:
```suggestion
- To run with `rocker`:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +If you locate your workspace under your home directory, you can use the `--home` option instead:
```suggestion
- If you locate your workspace under your home directory, you can use the `--home` option instead:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +To use a customized `.bashrc` for the container:
```suggestion
- To use a customized `.bashrc` for the container:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +To run with `rocker`:
```suggestion
- To run with `rocker`:
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +If you intend to use pre-existing data such as maps or Rosbags, modify the `--volume` options shown below.
```suggestion
- If you intend to use pre-existing data such as maps or Rosbags, modify the `--volume` options shown below.
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +3. Use `Visual Studio Code Remote - Containers`.
```suggestion
3. Use Visual Studio Code's `Remote - Containers` extension .
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +   You can use following settings. It creates a user account in a similar way as `rocker`.
```suggestion
To use the Remote-Containers extension, the following settings can be used to create a user account in a similar way to `rocker`.  
```

2022-01-28 08:24 UTC, LalithVipulananthan commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
```suggestion
Refer to [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
```

2022-01-28 15:15 UTC, kenji-miyake commented on docker/README.md
> +  We use `rocker` to enable GUI applications such as `rviz` and `rqt` on Docker Containers.
Actually, it was intended. I'll add `- ` for these lines.

2022-01-28 15:16 UTC, kenji-miyake commented on docker/README.md
> +### The development image
Could you tell me the reason and nuance, please? :pray:

2022-01-28 15:19 UTC, kenji-miyake commented on docker/README.md
> +You can use this image as below.
I'll resolve this since you did a new review.

2022-01-28 15:23 UTC, kenji-miyake commented on docker/README.md
> +We have two types of Docker images: `development` and `prebuilt`.
> Lines 15-22 should go immediately below the title rather than here, as these lines explain what the images do rather than how to use them.

Exactly, thank you!

> We should add a line at the very beginning to say These images provide all of the required dependencies for running Autoware in Docker.

Is this for beginners? I can't imagine some dependencies are missing in a Docker image.

2022-01-28 15:34 UTC, kenji-miyake commented on docker/README.md
> +The setup script in this repository will install these dependencies.
It's here, it uses Ansible. 
https://github.com/autowarefoundation/autoware/blob/e4631e136b8144a420a8969281bb0c57ad0acf8f/ansible/roles/docker/tasks/main.yaml

I'll write the installation steps here.
https://autowarefoundation.github.io/autoware-documentation/tier4-proposal/installation/autoware/docker-installation/

2022-01-28 15:37 UTC, kenji-miyake commented on docker/README.md
> +To use the development image image, run the following command:
Okay, will remove it.

2022-01-28 15:42 UTC, kenji-miyake commented on docker/README.md
> +It means it affects
Ah, I was writing something but it's not completed.

2022-01-28 15:42 UTC, kenji-miyake commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
Do we need `However` here? I feel it can be removed.

2022-01-28 15:44 UTC, kenji-miyake commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
BTW, I'll replace `permissions` with `privileges`.

2022-01-28 15:46 UTC, kenji-miyake commented on docker/README.md
> +It means it affects
I changed here to `It affects your local environment.`, is it okay or still should be removed?

2022-01-28 15:51 UTC, kenji-miyake commented on docker/README.md
> +1. Prepare a dedicated workspace for the docker image.
Mm, either one is fine. There are no priorities.
I just wanted to place rocker and VSCode side by side.

2022-01-28 15:52 UTC, kenji-miyake commented on docker/README.md
> +To run with `rocker`:
Could you write the reason?

2022-01-28 15:53 UTC, kenji-miyake commented on docker/README.md
> +If you build the images locally instead of pulling them from the server, run the following command:
Could you tell me the nuance?

2022-01-28 15:57 UTC, kenji-miyake commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
Could you tell me the nuance? (I'm sorry for asking so many times.)

> What is SemVar by the way?

https://semver.org/
But I'll change this to `tag`.

2022-01-28 16:00 UTC, kenji-miyake commented on docker/README.md
> +rocker --nvidia --x11 --user --volume {path_to_your_workspace} --volume {path_to_your_map_data} --volume {path_to_your_log_data} -- ghcr.io/autowarefoundation/autoware-universe:latest-prebuilt
Okay, I'll try not to overflow.
![image](https://user-images.githubusercontent.com/31987104/151579822-87e624af-4ff8-4033-84aa-8d709cd65bf6.png)

2022-01-28 16:04 UTC, kenji-miyake commented on docker/README.md
> +### Using other versions of images than `latest`
Mm, I'd like to write `images`...:thinking: Because it might mean the `latest` Docker client.
Are there any alternative sentences?

2022-01-28 16:05 UTC, kenji-miyake commented on docker/README.md
> +### Building Docker images on your local machine
Why do you think so?
I believe users don't use this so often.

2022-01-28 16:10 UTC, kenji-miyake commented on docker/README.md
> +If you locate your workspace under your home directory, you can use the `--home` option instead:
The same as https://github.com/autowarefoundation/autoware/pull/14#discussion_r794627524.

I'd appreciate it if you could write the reasons as well when you point out something. :pray: 
It's for not repeating the same mistakes in the future.

2022-01-28 16:10 UTC, kenji-miyake commented on docker/README.md
> +To use a customized `.bashrc` for the container:
The same as https://github.com/autowarefoundation/autoware/pull/14#discussion_r794627524.

2022-01-28 16:10 UTC, kenji-miyake commented on docker/README.md
> +To run with `rocker`:
The same as https://github.com/autowarefoundation/autoware/pull/14#discussion_r794627524.

2022-01-28 16:10 UTC, kenji-miyake commented on docker/README.md
> +If you intend to use pre-existing data such as maps or Rosbags, modify the `--volume` options shown below.
The same as https://github.com/autowarefoundation/autoware/pull/14#discussion_r794627524.

2022-01-28 16:15 UTC, kenji-miyake commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
Could you tell me the nuance for:
- Removing `Please`.
- Replacing `see` with `refer to`

Also, should I replace this line, too?

```
  - Please see [here](http://wiki.ros.org/docker/Tutorials/GUI) for more details.
```

2022-01-28 16:17 UTC, kenji-miyake commented on docker/README.md
> +To run with `rocker`:
The same as https://github.com/autowarefoundation/autoware/pull/14#discussion_r794627524.

2022-01-28 16:27 UTC, kenji-miyake commented on docker/README.md
> +   You can use following settings. It creates a user account in a similar way as `rocker`.
Applied in 1ef37665e2832fd3fcbac310c04b3209a85b8fb8, but I used `the extension` instead.

2022-01-28 16:27 UTC, kenji-miyake commented on docker/README.md
> +3. Use `Visual Studio Code Remote - Containers`.
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

2022-01-28 16:28 UTC, kenji-miyake commented on docker/README.md
> +rocker --nvidia --x11 --user --volume {path_to_your_workspace} --volume {path_to_your_map_data} --volume {path_to_your_log_data} -- ghcr.io/autowarefoundation/autoware-universe:latest-prebuilt
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

Is this okay?
![image](https://user-images.githubusercontent.com/31987104/151584583-88d70b2a-5cac-4426-807c-62446f93a004.png)

2022-01-28 16:29 UTC, kenji-miyake commented on docker/README.md
> +There are several recommended ways to prevent this.
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

2022-01-28 16:29 UTC, kenji-miyake commented on docker/README.md
> +It means it affects
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

Merged with the previous sentence.

2022-01-28 16:31 UTC, kenji-miyake commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

I wrote the following, is it okay?

```
If either image is run without `rocker`, then `root` privileges will be used.
This can affect your local environment.
```

2022-01-28 16:31 UTC, kenji-miyake commented on docker/README.md
> +### The prebuilt image
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

2022-01-28 16:31 UTC, kenji-miyake commented on docker/README.md
> +  We use `rocker` to enable GUI applications such as `rviz` and `rqt` on Docker Containers.
1ef37665e2832fd3fcbac310c04b3209a85b8fb8

How about this?

2022-01-28 16:32 UTC, kenji-miyake commented on docker/README.md
> +We have two types of Docker images: `development` and `prebuilt`.
Fixed in 1ef37665e2832fd3fcbac310c04b3209a85b8fb8, but didn't added `These images provide all of the required dependencies for running Autoware in Docker.` yet.

2022-01-31 14:08 UTC, xczhanjun commented
should replace all the rosdistro galactic in Dockerfile with ENV  ROS_DISTRO galactic and --rosdistro $ROS_DISTRO.

2022-01-31 14:14 UTC, kenji-miyake commented
> should replace all the rosdistro galactic in Dockerfile with ENV ROS_DISTRO galactic and --rosdistro $ROS_DISTRO.

@xczhanjun Why? Please write a reason when you ask for some changes.
We only support `Galactic` now. It will be updated to `Humble` after it's released.
Therefore, we only support only one package for a while. I don't want to increase the complexity for now.

2022-01-31 14:20 UTC, xczhanjun commented
> > should replace all the rosdistro galactic in Dockerfile with ENV ROS_DISTRO galactic and --rosdistro $ROS_DISTRO.
> 
> @xczhanjun Why? Please write a reason when you ask for some changes. We only support `Galactic` now. It will be updated to `Humble` after it's released. Therefore, we only support only one package for a while. I don't want to increase the complexity for now.

--- Thanks, you are so nice and great !

2022-02-01 05:35 UTC, LalithVipulananthan commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
You can combine those sentences I think.
> If either image is run without `rocker`, then `root` privileges will be used which can affect your local environment.

2022-02-01 05:36 UTC, LalithVipulananthan commented on docker/README.md
> +To run with `rocker`:
No strong reason. More a kind of stylistic choice to make the text stand out? If you would prefer not to have these lines as bullet points, then feel free to ignore this suggestion.

2022-02-01 05:37 UTC, LalithVipulananthan commented on docker/README.md
> +If you locate your workspace under your home directory, you can use the `--home` option instead:
See above. I will try to provide a justification for suggested changes going forwards.

2022-02-01 05:37 UTC, LalithVipulananthan commented on docker/README.md
> +To use a customized `.bashrc` for the container:
As noted above, this was purely a stylistic choice that can be ignored if you do not agree with it.

2022-02-01 05:38 UTC, LalithVipulananthan commented on docker/README.md
> +To run with `rocker`:
Stylistic choice that can be ignored if you do not agree with it.

2022-02-01 05:38 UTC, LalithVipulananthan commented on docker/README.md
> +If you intend to use pre-existing data such as maps or Rosbags, modify the `--volume` options shown below.
Stylistic choice that can be ignored if you do not agree with it.

2022-02-01 05:57 UTC, LalithVipulananthan commented on docker/README.md
> +If you run the following command, it uses the `root` permission.
This is fine.

2022-02-01 06:05 UTC, LalithVipulananthan commented on docker/README.md
> +There are several ways to prevent this error from occurring:
```suggestion
To prevent this error from occurring, there are two suggested methods:
```

Okay, the reason for this suggestion is:

- The lines above clearly state that this error can occur as a result of _not_ using `rocker` 
- So saying that `rocker` is a method seems like it's over-stating the point a little
- The sentence above is really saying `To prevent this error occurring (without using `rocker`)`

I hope that makes sense. If you really want to keep `rocker` in as a method of preventing the error, then I would put it at the top. However, I will defer to your judgement on this.

2022-02-01 06:05 UTC, LalithVipulananthan commented on docker/README.md
> +1. Prepare a dedicated workspace for the docker image.
See https://github.com/autowarefoundation/autoware/pull/14/files#r796285036

2022-02-01 06:08 UTC, LalithVipulananthan commented on docker/README.md
> +### Using other versions of images than `latest`
How about this?
> Using Autoware Docker images other than `latest`

You could also potentially omit `Autoware` from above.

2022-02-01 06:09 UTC, LalithVipulananthan commented on docker/README.md
> +### Building Docker images on your local machine
If users won't use it very often, then leaving it at the bottom is fine. I still think that building a local image is an alternative use case for the repository, rather than a tip, so it should have its own sub-heading and not be part of the Tips section (this is something I've seen in other GitHub repos containing Docker images)

2022-02-01 06:13 UTC, LalithVipulananthan commented on docker/README.md
> +If you build the images locally instead of pulling them from the server, run the following command:
If my understanding is correct, the whole point of the repo is to enable people to use images that have already been created, and so building the images locally is a deliberate choice and something that someone _wants_ to do versus something that they _need_ to do. It's a minor use case after all, as you pointed out.

If it still looks weird, you could just replace it with:
> To build the images locally, run the following command:

The reason for omitting the "instead of pulling them from the server" is that this is implied by doing a local build. Keeps the sentence shorter and more to the point.

2022-02-01 06:17 UTC, LalithVipulananthan commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
Stylistic choice again. I was having trouble coming up with a half-decent reason for it, but then I found this English Language Stack Exchange answer that answers it for me. 

In short, `refer` feels like the thing being referenced is an external link or document. `see` fits better when the reference is within the same document.
https://english.stackexchange.com/a/553294

2022-02-01 06:20 UTC, LalithVipulananthan commented on docker/README.md
> +The setup script in this repository will install these dependencies.
Okay. Perhaps the line above could be clarified with a link to the installation steps that you will write later? eg:
> The setup script in this repository will install these dependencies, as per the installation steps described [here](https://autowarefoundation.github.io/autoware-documentation/tier4-proposal/installation/autoware/docker-installation/).

Or something like that?

2022-02-01 07:52 UTC, kenji-miyake commented on docker/README.md
> +The setup script in this repository will install these dependencies.
@LalithVipulananthan It's nice! But I wouldn't like to add a reverse reference to autoware-documentation.
So I'd like to write this, how about it?

```markdown
The [setup script](../setup-dev-env.sh) will install these dependencies through the [docker role](../ansible/roles/docker/README.md).
```

2022-02-01 08:00 UTC, LalithVipulananthan commented on docker/README.md
> +We have two types of Docker images: `development` and `prebuilt`.
Fair enough. That sentence can be omitted then.

2022-02-01 08:01 UTC, kenji-miyake commented on docker/README.md
> +It means it affects
I assume it's okay seeing this comment.
https://github.com/autowarefoundation/autoware/pull/14#discussion_r796282382

2022-02-01 08:03 UTC, kenji-miyake commented on docker/README.md
> +  We use `rocker` to enable GUI applications such as `rviz` and `rqt` on Docker Containers.
I assume okay.
![image](https://user-images.githubusercontent.com/31987104/151932399-f9526bc6-4098-4e55-a87d-0df0a5718764.png)

2022-02-01 08:04 UTC, kenji-miyake commented on docker/README.md
> +To run with `rocker`:
Okay, then let me keep the current style so far. :bow:

2022-02-01 08:05 UTC, kenji-miyake commented on docker/README.md
> +### Using other versions of images than `latest`
Looks nice! Thank you.

2022-02-01 08:06 UTC, LalithVipulananthan commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
I should also explain why I took out the "please" - my understanding is that for technical writing, that word is often left out when giving instructions or when suggesting that a user look at some other documentation or reference ([here's the Tableau Server documentation to give one example](https://help.tableau.com/current/server/en-us/setup.htm))

2022-02-01 08:08 UTC, kenji-miyake commented on docker/README.md
> +If you build the images locally instead of pulling them from the server, run the following command:
Thank you for your clear answer!
Since I like simple expressions, I'll use `To build the images locally, run the following command:`.

2022-02-01 08:08 UTC, LalithVipulananthan commented on docker/README.md
> +### The development image
I thought I'd replied to this one. I can't really explain it, but here's the OSRF Docker image repo on GitHub. 
https://github.com/osrf/docker_images/blob/master/README.md#ros2--

If you look at the ROS 2 images, they are just listed by their names. So for example, `testing` rather than `the testing image`.

2022-02-01 08:09 UTC, kenji-miyake commented on docker/README.md
> +   You can use following settings. It creates a user account in a similar way as `rocker`.
I assume this can be resolved.

2022-02-01 08:10 UTC, kenji-miyake commented on docker/README.md
> +### Using other versions of images than `latest`
0ae86b1398968047cafbc817dc27253f9ae34cca

2022-02-01 08:10 UTC, kenji-miyake commented on docker/README.md
> +If you build the images locally instead of pulling them from the server, run the following command:
0ae86b1398968047cafbc817dc27253f9ae34cca

2022-02-01 08:12 UTC, kenji-miyake commented on docker/README.md
> +To run with `rocker`:
If there will be many suggestions for the style, I'll change it in another PR.
But will keep it as-is in this PR.

2022-02-01 08:15 UTC, kenji-miyake commented on docker/README.md
> +### The development image
Hmm, I see. English is very difficult for me. :cry:

2022-02-01 08:34 UTC, kenji-miyake commented on docker/README.md
> +### Building Docker images on your local machine
I feel if we prepare a sub-heading we need a sentence like this:

```markdown
## Building Docker images on your local machine

In case you want to ..., you can build images locally and use them.
``` 

I'm not sure what to write for `...`, so I'd like to keep it as a tip for now.

@LalithVipulananthan Is it okay?

2022-02-01 09:34 UTC, kenji-miyake commented on docker/README.md
> +1. Prepare a dedicated workspace for the docker image.
@LalithVipulananthan I'm sorry I can't find what you point out in the link (the browser doesn't auto-focus.). Could you attach a screenshot or copy the text?

2022-02-01 09:35 UTC, kenji-miyake commented on docker/README.md
> +1. Prepare a dedicated workspace for the docker image.
Ah, this?
![image](https://user-images.githubusercontent.com/31987104/151944514-58429d6a-c9dc-48f1-a630-baf19b29d768.png)

2022-02-01 09:43 UTC, kenji-miyake commented on docker/README.md
> +rocker --nvidia --x11 --user --volume {path_to_your_workspace} --volume {path_to_your_map_data} --volume {path_to_your_log_data} -- ghcr.io/autowarefoundation/autoware-universe:latest-prebuilt
I assume okay.

2022-02-01 10:02 UTC, kenji-miyake commented on docker/README.md
> +There are several ways to prevent this error from occurring:
Thank you! I've removed `rocker` from the option.
But I want to add `without rocker`.

```
To prevent this error from occurring without `rocker`, there are two suggested methods:
```

2022-02-01 10:08 UTC, kenji-miyake commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
Thank you, I understand!
Regarding `please`, I'll remove them in the document files, and leave them if they're in the interactive console.

2022-02-01 10:13 UTC, kenji-miyake commented on docker/README.md
> +   Please see [this document](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user) for more details.
78cf53d377430ae9a7c89db2c46a7664c4aa8f39

2022-02-01 10:14 UTC, kenji-miyake commented on docker/README.md
> +There are several ways to prevent this error from occurring:
78cf53d377430ae9a7c89db2c46a7664c4aa8f39

2022-02-02 02:07 UTC, LalithVipulananthan commented on docker/README.md
> +There are several ways to prevent this error from occurring:
Maybe this?
> To prevent this error occurring when `rocker` is not used, there are two suggested methods:

2022-02-02 02:08 UTC, kenji-miyake commented on docker/README.md
> +There are several ways to prevent this error from occurring:
:+1:

2022-02-02 02:08 UTC, LalithVipulananthan commented on docker/README.md
> +The setup script in this repository will install these dependencies.
That looks fine to me.

2022-02-02 02:10 UTC, kenji-miyake commented on docker/README.md
> +There are several ways to prevent this error from occurring:
Thank you, fixed in e99e6f9abeb02bb0ff503d8f5d11da98c1cae30a.

2022-02-02 02:12 UTC, LalithVipulananthan commented on docker/README.md
> +### Building Docker images on your local machine
That's fine. We can always revisit at a later date.

2022-02-02 02:19 UTC, LalithVipulananthan commented on docker/README.md
> +### Building Docker images on your local machine
The example I was referencing was [found here](https://github.com/linuxserver/docker-wireguard): 
![image](https://user-images.githubusercontent.com/63835446/152083194-bcca61b4-6ac5-41ec-9620-baa180654a4e.png)

If you prefer to keep it as a tip then that is also fine.

2022-02-02 02:26 UTC, LalithVipulananthan commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
"version" is not a verb so "versioned" looks wrong to me. I have a feeling that it is being used like this by developers however.

> https://semver.org/
> But I'll change this to `tag`.

Okay. In which case, I think it would be better to clarify the meaning of `SemVar` by including a link to the page above, or just putting `(semantic version)` after `SemVar`. Changing `SemVar` to `tag` makes it even less clear what is meant. 

An alternative sentence suggestion:
> There are also other images available that are tagged by either `date` or `SemVer` (semantic version).

2022-02-02 03:20 UTC, kenji-miyake commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
Actually, a tag sometimes isn't SemVer because it has a suffix like `v0.1.2-beta`, so writing `SemVer` here is not strictly correct. :thinking:

2022-02-02 03:20 UTC, kenji-miyake commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
@LalithVipulananthan How about `release tag` or `software release tag`?

2022-02-02 03:29 UTC, kenji-miyake commented on docker/README.md
> +### Building Docker images on your local machine
Okay, thank you!
I'll add `development purposes` and create a section.

2022-02-02 03:42 UTC, kenji-miyake commented on docker/README.md
> +### Building Docker images on your local machine
766f9e8a21a12a73aaea7b16e6fc51fcbee7d506

2022-02-02 03:43 UTC, kenji-miyake commented on docker/README.md
> +There are also images versioned based on the `date` or `SemVer`.
Used `release tag` in 766f9e8a21a12a73aaea7b16e6fc51fcbee7d506.

2022-02-02 05:00 UTC, LalithVipulananthan approved these changes
Changes approved!

2022-02-02 09:40 UTC, kenji-miyake commented
@mitsudome-r @xmfcx Since we've done native checks and technical writing checks, I'll merge this and test it.

2022-02-02 09:41 UTC, merged