fix(update-docker-manifest): fix broken workflow
autowarefoundation/autoware_core_universe_prototype pull request #181
Opened 2022-04-17 03:12 UTC by kenji-miyake

## Description

Fixed the `update-docker-manifest` workflow.
https://github.com/autowarefoundation/autoware/runs/6051121373?check_suite_focus=true

- The page number is necessary.
  - https://docs.github.com/en/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-an-organization
- Sometimes a certain architecture's version is missing. (Due to the build failure.)
  - For example, `20220417` in https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/versions

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-04-17 03:12 UTC, kenji-miyake commented
Testing: https://github.com/autowarefoundation/autoware/runs/6051473814?check_suite_focus=true

2022-04-17 03:21 UTC, kenji-miyake commented
I'll fix this issue.
https://github.com/autowarefoundation/autoware/runs/6051508580?check_suite_focus=true#step:3:110

2022-04-18 09:50 UTC, kenji-miyake commented
Worked. https://github.com/autowarefoundation/autoware/runs/6061140395?check_suite_focus=true

2022-04-18 11:16 UTC, esteve requested changes

2022-04-18 11:16 UTC, esteve commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
Given that the logic for this job has increased in complexity, I think it'd be best if moved to a script in a file

2022-04-18 11:20 UTC, kenji-miyake commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
Thank you. Okay, I'll change the code. :+1:

2022-04-23 13:35 UTC, kenji-miyake commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
@esteve Since the script uses GitHub context variables `${{ }}`, it was difficult to move to a script.

Instead, I've split it into a composite action (so that we can reuse it for another image) and split the script into several steps.

How about it? 
https://github.com/autowarefoundation/autoware/runs/6140421180?check_suite_focus=true

2022-04-25 14:30 UTC, kenji-miyake commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
@esteve Just in case you missed it, friendly ping. Could you please take a look? :bow:

2022-04-25 14:37 UTC, esteve approved these changes

2022-04-25 14:38 UTC, merged

2022-04-25 14:38 UTC, esteve commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
@kenji-miyake done 🙂

2022-04-25 14:38 UTC, kenji-miyake commented on .github/workflows/update-docker-manifest.yaml
>            package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
Thank you so much. :pray: