fix(ansible/rocker): use ROS 2 apt repository for Ubuntu 22.04
autowarefoundation/autoware_core_universe_prototype pull request #242
Opened 2022-04-27 10:48 UTC by kenji-miyake

## Description

There isn't `jammy` in the `ros` repository, but is in the `ros2` repository.

http://packages.ros.org/ros/ubuntu/dists/
http://packages.ros.org/ros2/ubuntu/dists/

This causes an error https://github.com/autowarefoundation/autoware/discussions/239#discussioncomment-2645081.

I confirmed `python3-rocker` is listed here.
http://packages.ros.org/ros2/ubuntu/dists/jammy/main/binary-amd64/Packages

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-04-27 10:52 UTC, kenji-miyake commented
Ah, I have to fix the document as well.

2022-04-28 10:07 UTC, esteve requested changes

2022-04-28 10:07 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> +- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
It's better to use `lsb_release -cs` as it's defined by the LSB standard

2022-04-28 10:10 UTC, esteve requested changes

2022-04-28 10:10 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> +    dest: /usr/share/keyrings/ros-archive-keyring.gpg
The keyring may contain other keys, it's better to add it via `ansible.builtin.apt_key`

2022-04-28 10:11 UTC, esteve requested changes

2022-04-28 10:11 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> -    repo: deb http://packages.ros.org/ros/ubuntu {{ lsb_release_cs.stdout }} main
I think just updating the URL from `http://packages.ros.org/ros/ubuntu` to `http://packages.ros.org/ros2/ubuntu` is enough, there's no need to add these extra steps in this task.

2022-04-28 11:17 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> +- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
Hmm? But ROS 2 replaced it with `UBUNTU_CODENAME`. 
https://github.com/ros2/ros2_documentation/pull/2104

2022-04-28 11:20 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> +    dest: /usr/share/keyrings/ros-archive-keyring.gpg
I just followed this page. Could you explain the problem a bit more in detail?
https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Binary.html#add-the-ros-2-apt-repository

2022-04-28 11:21 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> -    repo: deb http://packages.ros.org/ros/ubuntu {{ lsb_release_cs.stdout }} main
What are the extra steps? I believe they all are in this installation guide. :thinking: 
https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Binary.html#add-the-ros-2-apt-repository

2022-04-28 12:01 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> -    repo: deb http://packages.ros.org/ros/ubuntu {{ lsb_release_cs.stdout }} main
I meant in this PR, we only need to update the URL, we don't need the extra tasks (i.e. `deb_architecture`, `ubuntu_codename`). The code we had before was enough.

2022-04-28 12:02 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> +- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
But it only works with Ubuntu, whereas `lsb_release -cs` is standard for all Linux distributions, so the current code works for Debian as well.

2022-04-28 12:03 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> -    repo: deb http://packages.ros.org/ros/ubuntu {{ lsb_release_cs.stdout }} main
Technically, it's true.

But,
- `/usr/share/keyrings` is the recommended way to manage keys.
- We already use this way in the [ros2](https://github.com/autowarefoundation/autoware/blob/f6a2b5254050d2a055a693e075fef598ea0b744e/ansible/roles/ros2/tasks/main.yaml) role. We don't have to duplicate the key.

2022-04-28 12:04 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> +    dest: /usr/share/keyrings/ros-archive-keyring.gpg
`ansible.builtin.apt_key` correctly calls `apt-key add` to add a remote key, `get_url` replaces the file in the filesystem with a remote file. If there are any other keys in that keyring, `get_url` will overwrite them, but `apt_key` will add the new key while maintaining the existing key.

2022-04-28 12:05 UTC, esteve requested changes
Just updating the URL is enough, we don't need to change anything else in the `main.yaml` file

2022-04-28 12:07 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> +- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
I see. Then it's okay to use `lsb_release -cs` for the Docker-related roles.

2022-04-28 12:13 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> +- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
Replaced it in 9e914d29a5db4ba0b4b197600b06f0044e5214ed.

2022-04-28 12:20 UTC, kenji-miyake commented on ansible/roles/rocker/tasks/main.yaml
> +    dest: /usr/share/keyrings/ros-archive-keyring.gpg
I think it's not a recommended way and replaced in this PR. Do you really recommend using `apt_key`? :thinking: 
https://github.com/ros2/ros2_documentation/pull/1189

2022-04-28 12:35 UTC, esteve commented on ansible/roles/rocker/tasks/main.yaml
> +    dest: /usr/share/keyrings/ros-archive-keyring.gpg
You're right, according to https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_Key_distribution

> The key MUST be downloaded over a secure mechanism like HTTPS to a location only writable by root, which SHOULD be /usr/share/keyrings. The key MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add. 

Thanks for the link :+1:

2022-04-28 12:39 UTC, esteve approved these changes
Thanks for addressing my feedback :+1:

2022-04-28 12:39 UTC, merged