chore: add issue and PR templates
autowarefoundation/autoware_core_universe_prototype pull request #56
Opened 2022-02-13 14:09 UTC by kenji-miyake

Added templates.
Please refer to https://github.com/kenji-miyake/test-pr-template about its behavior.

References:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

2022-03-09 08:37 UTC, isamu-takagi submitted a review, later dismissed
Great, I confirmed the behavior in the demo repository.

2022-03-09 08:38 UTC, kenji-miyake commented
Thank you!
I'll wait for @xmfcx or @mitsudome-r to approve this.

2022-03-13 06:04 UTC, xmfcx requested changes
I've also tested it in a fork and seems to be working well. I hope people can read and actually press the `Preview` button and select a template.

That feels so hacky, surprised github doesn't provide native support for this.

2022-03-13 06:04 UTC, xmfcx commented on .github/PULL_REQUEST_TEMPLATE/small-change.md
> +- [ ] There are no open points or they are tracked via tickets.
```suggestion
- [ ] There are no open discussions or they are tracked via tickets.
```

2022-03-13 06:14 UTC, xmfcx requested changes
Missed this one.

2022-03-13 06:14 UTC, xmfcx commented on .github/PULL_REQUEST_TEMPLATE/standard-change.md
> +- [ ] There are no open points or they are tracked via tickets.
```suggestion
- [ ] There are no open discussions or they are tracked via tickets.
```

2022-03-13 06:14 UTC, kenji-miyake commented
FYI, I'll link a thread on GitHub Community Forum.
https://github.community/t/is-there-a-pull-request-template-selector-similar-to-issues/171838

2022-03-13 06:15 UTC, xmfcx approved these changes

2022-03-13 06:22 UTC, merged